packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: f54abe6f1f9b1eb7923e442fa11f3cf16ad5cfcb
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: 719f81d1b8b1c8f870966c07e96765c1f470ccf5
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 2edee3b36f8d030c4feed51f8430d6e15d16123f
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 14d06448def366d9df83aabe5a2da091fa43c000
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 1e7ff5df8fd7dff345e2d68813212546540bba25
  extra-dep: True
- location:
    git: https://github.com/lamdu/language-ecmascript
    commit: 1c75cfd064faec8c564c205702227bb44822e296
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: cb9831476fa66b65c0d40537d55af85fd03b00c7
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- uuid-aeson-0.1.0.0
- List-0.5.2

extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
resolver: lts-7.9
