packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 753fb81d50abf622da907420f1956ec12542cfa9
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: 6eb15fb8eefffbeec460c3865da767b72cd7f787
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: adf091973d26e80fac49764f03865f3e38a18c23
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 5a16cfb95490b3dbb019ff27a28ba4b63218d056
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 286b75894e51b08b7c63f8845f045f66d27e9849
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 614cfa868899f2dde5801e1b95d4bc43815e9851
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- language-ecmascript-0.17.2.0
- stb-image-0.2.1
- GLFW-b-1.4.8.1
- testing-feat-0.4.0.3
- tagshare-0.0

resolver: lts-10.5

allow-newer: true
