packages:
- '.'
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0
- language-ecmascript-0.19.1.0
- github: lamdu/bindings-freetype-gl
  commit: 440ee6a7a5f25ebc24e087d0d3ea9f588da6bb93
- github: lamdu/lamdu-calculus
  commit: 4876da8f515670cefc18e58aa00a0839bf08ff9a
- github: lamdu/momentu
  commit: 60056deffb52c453839a058fc70ee779b25269bb
- github: lamdu/hypertypes
  commit: 9d1f54b4c5a60c39f08b5559e2f5bdd3efdfe975
- github: lamdu/graphics-drawingcombinators
  commit: 39500dd189b0676468848d1f452ac31c7f0ec461
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4
- github: lamdu/leveldb-haskell
  commit: 6f2f0b88fd7197e74cbff92bde94168adce3fb29
- github: lamdu/FreetypeGL
  commit: 18ca298d8fd48ad18f75264553b57714bf070c77
- github: tweag/inline-js
  commit: 5da3690abd454e5e94021dcd4486484e89fc419f
  subdirs:
    - inline-js-core

resolver: lts-18.12

allow-newer: true

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

# require-stack-version: ">=2.5"
