resolver: lts-23.23

packages:
  - '.'
extra-deps:
  - bitmap-0.0.2
  - bitmap-opengl-0.0.1.5
  - stb-image-0.2.1
  - unicode-properties-3.2.0.0
  - inline-c-objc-0.1.0.0
  - storable-offset-0.1.0.0
  - github: jswebtools/language-ecmascript
    commit: a1e47e69e68f6f70f8eca40d28dd8b702262a123
    # nix-sha256: sha256-W9mVrw/1uFBcu9l1Sud73H34OGC7iiChulRLSTwFSnU=
  - github: lamdu/text-trie
    commit: 07124aa86ec0edf6685c2f916f812f8ae0261693
    # nix-sha256: sha256-ax3ehv9qsKJWrDcorG7QTxkzdeKq9h6ExpO354/oLrE=
  - github: lamdu/rocksdb-haskell
    commit: c0b13d11784fff618f6a459e1570bb0b369d2551
    # nix-sha256: sha256-/FY2WksoIH8d6l2PnKR02qMlHI3AG1w96VwhtqwjiAY=
  - github: lamdu/bindings-freetype-gl
    commit: 4cef7d3f44b088d3d8644bc9acc97951820bd3ba
    # nix-sha256: sha256-7X2QVV0N66djBpVTYK+0u5mP19sYAo3EBn4ggZUrMvg=
  - github: lamdu/lamdu-calculus
    commit: 21332a4c1576ad028bbb693b23e8943089256ef8
    # nix-sha256: sha256-jtph3fmpiK/31eOKgmPRD+OMHtKOpvKzbI8iYWeLj84=
  - github: lamdu/momentu
    commit: c844afbfc95fb7391f9b9d1023630fea40a3fc9f
    # nix-sha256: sha256-f7SYcjGn8XCCCglowCLyY3HUuQfswP2Zz78Zst5kc6s=
  - github: lamdu/GLFW-b
    commit: 506abf792cfd98f9a4e6d0bc526b74f848dc413e
    # nix-sha256: sha256-xkL11JjQXG62xTE4sgCIU+kxQCPIJ4/j6aOrXns+oPE=
  - github: lamdu/bindings-GLFW
    commit: 4402c6b6fee81e59f5931fabe1724233cd0ca08c
    # nix-sha256: sha256-+VC2eLVeaxtOrsisOPlgc5wJHN951x17PStwiqDXQnE=
  - github: lamdu/hypertypes
    commit: 06cf48ef9c85c54cbe722a448754cb89931b23e7
    # nix-sha256: sha256-t1iGRLUCv01gDeHjbWP8NyyLgXgaDW26BaCFlQ5R4NQ=
  - github: lamdu/graphics-drawingcombinators
    commit: 39500dd189b0676468848d1f452ac31c7f0ec461
    # nix-sha256: sha256-2IQJQ7wGblnCRgzRFz90vUsqs2YBthNlXEvZ1gkrlgA=
  - github: lamdu/freetype2
    commit: f59a2ab94621364db78a50fdd23c2b11e773a503
    # nix-sha256: sha256-HJzsbDgI+vOHavAyfn+P4g9sAJhynR/8Vg9hkLklRl8=
  - github: lamdu/FreetypeGL
    commit: 18ca298d8fd48ad18f75264553b57714bf070c77
    # nix-sha256: sha256-PGcCI21gUUo54PZGi1Ca5M9FbXLZUb4O74Ve0P1dR7A=
  - github: tweag/inline-js
    commit: 8512b09d2c0533a41d5d2aef182b11a58c420c10
    # nix-sha256: sha256-Hgiq8LJKLLpuMwmjlF3IeHTW2qBipMV6Q7up+mVKlVA=
    subdirs:
    - inline-js-core

allow-newer: true

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

flags:
  bindings-GLFW:
    ExposeNative: true

# require-stack-version: ">=2.5"
