name: Nix Flake

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: "Build Nix Flake"
        run: nix build
